---
- id: semver
  name: semver
  description: Check semver crate version considering potential breaking changes.
  entry: cargo semver-checks check-release
  language: system
  types: [rust]
  pass_filenames: false
- id: audit
  name: audit
  description: Check outdated deps and cargo audit
  entry: cargo outdated -wR && cargo audit --deny warnings
  language: system
  types: [rust]
  pass_filenames: false
