---
- id: semver
  name: semver
  description: Check semver crate version considering potential breaking changes.
  entry: cargo semver-checks check-release
  language: system
  types: [rust]
  pass_filenames: false
