---
  - id: cargo-check-semver
    name: cargo check semver
    description: Check semver crate version considering potential breaking changes.
    entry: cargo semver-checks check-release
    language: system
    types: [rust]
    pass_filenames: false

  - id: cargo-audit
    name: cargo audit
    description: Check cargo audit
    entry: cargo audit --deny warnings
    language: system
    types: [rust]
    pass_filenames: false

  - id: cargo-outdated
    name: cargo outdated
    description: Check outdated deps
    entry: cargo outdated -wR
    language: system
    types: [rust]
    pass_filenames: false

  - id: cargo-tests-all
    name: cargo tests all features
    description: cargo test all features
    entry: cargo test --all-features -- --nocapture
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-all-possible-broken-code
    name: clippy all with autofix and possible broken code
    description: clippy all with autofix and possible broken code
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps --broken-code -- --no-deps
      -D warnings -Wmissing_docs -W clippy::all
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-all
    name: clippy all with autofix
    description: clippy all with autofix
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps -- --no-deps -D warnings
      -Wmissing_docs -W clippy::all
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-pedantic-possible-broken-code
    name: clippy pedantic with autofix and possible broken code
    description: clippy pedantic with autofix and possible broken code
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps --broken-code -- --no-deps
      -D warnings -W clippy::pedantic
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-pedantic
    name: clippy pedantic with autofix
    description: cargo clippy pedantic
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps -- --no-deps -D warnings
      -W clippy::pedantic
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-nursery-possible-broken-code
    name: clippy nursery with autofix and possible-broken-code
    description: clippy nursery with autofix and possible-broken-code
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps --broken-code -- --no-deps
      -D warnings -W clippy::nursery
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-nursery
    name: clippy nursery with autofix
    description: clippy nursery with autofix and possible-broken-code
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps -- --no-deps -D warnings
      -W clippy::nursery
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-others-possible-broken-code
    name: clippy correctness suspicious style complexity perf with autofix and possible broken code
    description: clippy correctness suspicious style complexity perf with autofix and possible broken code
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps --broken-code -- --no-deps
      -D warnings -W clippy::cargo -W clippy::correctness -W clippy::suspicious -W clippy::style -W clippy::complexity -W clippy::perf
    language: system
    types: [rust]
    pass_filenames: false

  - id: clippy-autofix-others
    name: clippy correctness suspicious style complexity perf with autofix
    description: clippy correctness suspicious style complexity perf with autofix and possible broken code
    entry: cargo clippy --all-targets --all-features --workspace --fix -Z unstable-options --allow-dirty --allow-staged --no-deps -- --no-deps -D warnings
      -W clippy::cargo -W clippy::correctness -W clippy::suspicious -W clippy::style -W clippy::complexity -W clippy::perf
    language: system
    types: [rust]
    pass_filenames: false

  - id: cargo-format
    name: cargo-format
    description: cargo format
    entry: cargo fmt --all -- --unstable-features --config edition="2021",imports_granularity="Crate",format_macro_matchers=true,format_strings=true,reorder_impl_items=true,group_imports="StdExternalCrate",unstable_features=true,use_field_init_shorthand=true
    language: system
    types: [rust]
    pass_filenames: false

  - id: cargo-dry-publish
    name: cargo-dry-publish
    description: cargo publish (dry)
    entry: cargo publish --dry-run
    language: system
    types: [rust]
    pass_filenames: false

  - id: dprint-toml-fix
    name: dprint-toml-fix
    description: dprint linter/formatter (in Rust)
    entry: dprint --config https://raw.githubusercontent.com/Manuthor/git-hooks/main/dprint.json fmt -- '**/*.toml'
    language: system
    types: [text]
    pass_filenames: false
